### PR TITLE
added project charters page and overview to README.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by kerchner** [comment]
@dchud this pull request is still valid, when you have a chance to take a look.

**Comment by kerchner** [comment]
@dchud can we just merge this, and then review and modify as needed?

**Comment by kerchner** [comment]
@justinlittman @lwrubel any objections if I merge this?  We can always re-evaluate and make further changes from that baseline.

**Comment by lwrubel** [comment]
no objections

**Pull request merged**
